// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uqeb.Api.Data;

#nullable disable

namespace Uqeb.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623175715_AddReportNumberSequences")]
    partial class AddReportNumberSequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplyDueDays")
                        .HasColumnType("int");

                    b.Property<int>("ReplyStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReplySummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReply")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DueDate");

                    b.HasIndex("TransactionId");

                    b.HasIndex("DepartmentId", "Status", "ReplyStatus");

                    b.HasIndex("TransactionId", "RequiresReply", "ReplyStatus", "Status");

                    b.HasIndex("DepartmentId", "Status", "RequiresReply", "ReplyStatus", "DueDate");

                    b.HasIndex("Status", "RequiresReply", "ReplyStatus", "DueDate", "DepartmentId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("TransactionId", "CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.ExternalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique();

                    b.ToTable("ExternalParties");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FollowUpNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReplyStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReplySummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReply")
                        .HasColumnType("bit");

                    b.Property<string>("SentTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TransactionId", "CreatedAt");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUpDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FollowUpId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("FollowUpDepartments");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUpRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("FollowUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPartyId");

                    b.HasIndex("FollowUpId", "ExternalPartyId")
                        .IsUnique();

                    b.ToTable("FollowUpRecipients");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.LetterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LetterTemplates");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.LoginAttemptLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("IpAddress", "OccurredAt");

                    b.HasIndex("Succeeded", "OccurredAt");

                    b.HasIndex("Username", "OccurredAt");

                    b.ToTable("LoginAttemptLogs");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.ReportExportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFiltersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultFormat")
                        .HasColumnType("int");

                    b.Property<bool>("IncludePartialCover")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludePartialManifest")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumberingMode")
                        .HasColumnType("int");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<string>("SectionIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportExportTemplates");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.SecurityAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead", "CreatedAt");

                    b.HasIndex("Severity", "CreatedAt");

                    b.HasIndex("Type", "CreatedAt");

                    b.ToTable("SecurityAlerts");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncomingFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IncomingFromDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("IncomingFromPartyId")
                        .HasColumnType("int");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IncomingSourceType")
                        .HasColumnType("int");

                    b.Property<string>("InternalTrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OutgoingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutgoingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutgoingToPartyId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresResponse")
                        .HasColumnType("bit");

                    b.Property<bool>("ResponseCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResponseCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseDueDays")
                        .HasColumnType("int");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IncomingDate");

                    b.HasIndex("IncomingFromDepartmentId");

                    b.HasIndex("IncomingFromPartyId");

                    b.HasIndex("IncomingNumber")
                        .IsUnique();

                    b.HasIndex("IncomingSourceType");

                    b.HasIndex("InternalTrackingNumber")
                        .IsUnique();

                    b.HasIndex("IsArchived");

                    b.HasIndex("OutgoingDate");

                    b.HasIndex("OutgoingToPartyId");

                    b.HasIndex("ResponseCompleted");

                    b.HasIndex("ResponseDueDate");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("CategoryId", "IncomingDate");

                    b.HasIndex("IncomingSourceType", "IncomingDate");

                    b.HasIndex("RequiresResponse", "ResponseCompleted", "ResponseDueDate");

                    b.HasIndex("Status", "IncomingDate", "ClosedAt");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.TransactionOutgoingDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId", "TransactionId");

                    b.HasIndex("TransactionId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("TransactionOutgoingDepartments");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.TransactionOutgoingParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("ExternalPartyId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExternalPartyId");

                    b.HasIndex("TransactionId", "ExternalPartyId")
                        .IsUnique();

                    b.ToTable("TransactionOutgoingParties");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Assignment", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Department", "Department")
                        .WithMany("Assignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("Assignments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Attachment", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("Attachments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Uqeb.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUp", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("FollowUps")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUpDepartment", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Department", "Department")
                        .WithMany("FollowUpDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.FollowUp", "FollowUp")
                        .WithMany("Departments")
                        .HasForeignKey("FollowUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("FollowUp");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUpRecipient", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.ExternalParty", "ExternalParty")
                        .WithMany()
                        .HasForeignKey("ExternalPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.FollowUp", "FollowUp")
                        .WithMany("Recipients")
                        .HasForeignKey("FollowUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalParty");

                    b.Navigation("FollowUp");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Transaction", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.Category", "CategoryEntity")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Department", "IncomingFromDepartment")
                        .WithMany("IncomingTransactions")
                        .HasForeignKey("IncomingFromDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Uqeb.Api.Models.Entities.ExternalParty", "IncomingFromParty")
                        .WithMany()
                        .HasForeignKey("IncomingFromPartyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Uqeb.Api.Models.Entities.ExternalParty", "OutgoingToParty")
                        .WithMany()
                        .HasForeignKey("OutgoingToPartyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Uqeb.Api.Models.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoryEntity");

                    b.Navigation("CreatedBy");

                    b.Navigation("IncomingFromDepartment");

                    b.Navigation("IncomingFromParty");

                    b.Navigation("OutgoingToParty");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.TransactionOutgoingDepartment", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Department", "Department")
                        .WithMany("OutgoingTransactions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("OutgoingDepartments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.TransactionOutgoingParty", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.ExternalParty", "ExternalParty")
                        .WithMany()
                        .HasForeignKey("ExternalPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Uqeb.Api.Models.Entities.Transaction", "Transaction")
                        .WithMany("OutgoingParties")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ExternalParty");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.User", b =>
                {
                    b.HasOne("Uqeb.Api.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Department", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("FollowUpDepartments");

                    b.Navigation("IncomingTransactions");

                    b.Navigation("OutgoingTransactions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.FollowUp", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Uqeb.Api.Models.Entities.Transaction", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("FollowUps");

                    b.Navigation("OutgoingDepartments");

                    b.Navigation("OutgoingParties");
                });
#pragma warning restore 612, 618
        }
    }
}
